### ISSUE TITLE
[Feature] 

### ISSUE THREAD

**Issue by ghost** [jngo102/Butterfly#1]
### Describe the problem

What should you write here

### Describe the feature that you'd like

A button to reset all globalsettings

**Comment by jngo102** [comment]
What does this entail? It is not reasonably feasible to reset the global settings of every mod to their default value. What I can do is delete the global settings so that when you boot up the game again the settings are regenerated with their initial values.

Next time, please be more descriptive of the feature you are proposing.

**Comment by ghost** [comment]
Meant deleting the globalsettings

**Comment by jngo102** [comment]
The requested feature has been added. Please refer to the latest release [12.04.2022](https://github.com/jngo102/Butterfly/releases/tag/12.04.2022) to download the updated installer.
